name: Create Release
# This workflow is triggered when tagging with v*
# example:
# git tag v0.0.22-beta
# git push origin v0.0.22-beta

on: 
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
          server-id: github

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install python requirements
        run: pip install -r .github/scripts/requirements.txt    

      - name: Setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.6.3

      - name: configure-git-user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: get-pom-version
        id: pom-version
        run: |
          echo "JAVA_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: print-pom-version    
        run: echo "JAVA_POM_VERSION=${{ steps.pom-version.outputs.JAVA_POM_VERSION }}"

      - name: check-package-exist
        id: check_package_exist
        run: python3 .github/scripts/existsGitHubPackageVersion.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          PACKAGE_TYPE: maven
          PACKAGE_NAME: com.opentelekomcloud.opentelekomcloud-functiongraph-java
          PACKAGE_VERSION_NAME: ${{ steps.pom-version.outputs.JAVA_POM_VERSION }}
          OUTPUT_NAME: PACKAGE_EXISTS

      - name: echo-if-package-exists
        if: "${{ steps.check_package_exist.outputs.PACKAGE_EXISTS == 'true' }}"
        run: echo "::notice::Package exsits, skipping upload."

      - name: deploy-package-to-github
        if: "${{ steps.check_package_exist.outputs.PACKAGE_EXISTS != 'true' }}"
        id: deploy_github
        run: |
          echo "::notice::Uploading Package ..."
          mvn -B deploy --file pom.xml \
            -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
      # https://github.com/ncipollo/release-action/blob/main/.github/workflows/release.yml
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          generateReleaseNotes: true
          body: ""
